# This workflow manages to test this repository.
name: main

on:
  push:
    paths:
      - "up_aries/bin/*"

jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: python3 -m pip install unified-planning pytest

      - name: Install UP-Aries
        run: python3 -m pip install .

      - name: Run tests
        run: python3 -m pytest -v tests