# This workflow manages to test this repository.
name: Test Planner

on:
  push:
  schedule:
    - cron: "0 2 15 * *"
    - cron: "0 2 1 * *"
jobs:
  test-up-aries:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]
    defaults:
      run:
        shell: bash
    runs-on: ${{ matrix.os }}
    name: Test - ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: git clone https://github.com/aiplan4eu/unified-planning.git -b aries-engine && cd unified-planning && pip install .

      - name: Install UP-Aries
        run: python3 -m pip install .

      - name: Test executable
        run: |
          brew install coreutils
          ll ./up_aries/bins
          timeout 10s ./up_aries/bins/aries_macos_x86_64

      - name: Run tests
        run: python3 -m pytest -v up_aries/test_planner.py
