# Build cargo repository for all platforms

name: Aries Compile CI - Windows

on:
  schedule:
    - cron: "0 2 15 * *"
    - cron: "0 2 1 * *"

env:
  GITHUB_BRANCH: compile-ci

jobs:
  build-windows:
    runs-on: windows-latest
    name: Build Aries - windows-latest-amd64

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ env.GITHUB_BRANCH }}

      - uses: actions-rs/toolchain@v1
        name: Install Rust
        with:
          toolchain: stable
          override: true

      - name: Clone Aries and Build
        run: |
          git clone https://github.com/plaans/aries.git --branch master
          cd aries
          cargo build --release --bin up-server

          cp target/release/up-server.exe ../up_aries/bins/aries_windows_amd64.exe
          cd ..
          strip up_aries/bins/aries_windows_amd64.exe # Strip the binary to reduce size
          bash .github/ci/github.sh amd64 windows

  test-windows:
    runs-on: windows-latest
    name: Test Aries - windows-latest-amd64
    needs: build-windows

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ env.GITHUB_BRANCH }}

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install Python Dependencies
        run: |
          git clone https://github.com/aiplan4eu/unified-planning.git -b aries-engine && cd unified-planning && pip install .

      - name: Install Up-Aries
        run: |
          python3 -m pip install .

      - name: Run Tests
        run: |
          python3 -m pip install pytest
          python3 -m pytest -v up_aries/test_planner.py
